django/learning_log/learning_log/learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('learning_logs.urls', namespace='learning_logs')),
]

django/learning_log/learning_log/learning_logs/urls.py
from django.conf.urls import url
from . import views

# Expressao regular:
# r -> raw text
#^ -> inicio do texto
#$ -> final do texto
# r'^$' -> expressao regular para texto vazio


urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Testeeeee
    url(r'^teste/$', views.teste, name='teste'),
    # Exibir todos os topicos
    url(r'^topics/$', views.topics, name='topics'),
    # Pagina para um topico unico
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # Get topic
    url(r'^topics/get/(?P<topic_id>\d+)/$', views.getTopic, name='getTopic'),
    # Pagina para adicionar um novo topico
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Página para adicionar nova entrada
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # Página para editar entrada
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

django/learning_log/learning_log/learning_logs/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'topico'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'entrada'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

class Teste(models.Model):
    teste = models.TextField()
    teste2 = models.DateTimeField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.teste2)

django/learning_log/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

django/learning_log/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
# tentando enviar em Json!
from django.http import JsonResponse

# Create your views here.


def index(request):
    """Home page"""
    return render(request, 'index.html')
# testeeeeee


def teste(request):
    """Testeeeeeee"""
    return render(request, 'teste.html')
# topics


def topics(request):
    """Topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)


# topic
def topic(request, topic_id):
    """Topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries
    }
    return render(request, 'topic.html', context)


# getTopic
def getTopic(request, topic_id):
    """getTopic"""
    topic = Topic.objects.get(id=topic_id)
    topic_list = list(topic)
    # return render(request,context)
    return JsonResponse(topic_list, safe=False)

# Adicionar um novo topico


def new_topic(request):
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TopicForm()
    else:
        # POST
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {
        'form': form
    }
    return render(request, 'new_topic.html', context)

# Nova entrada


def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)

# Editar entrada


def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry.html', context)

django/learning_log/learning_log/learning_logs/templates/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <p><a href="{% url 'learning_logs:teste' %}">TESTTEEEEEEEEEEEE</a></p>
    <p><a href="{% url 'learning_logs:topics' %}">Topics</a></p>
</p>
{% block content %}{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/edit_entry.html
{% extends "base.html" %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	<p>Editar entrada:</p>

	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">salvar mudanças</button>
	</form>
{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/index.html
{% extends "base.html" %}
{% block content %}
<p>Learning Log te ajuda a manter o registro de seu aprendizado para qualquer tópico sobre o qual você esteja aprendendo.</p>
{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/new_entry.html
{% extends "base.html" %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Adicionar nova entrada:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">adicionar entrada</button>
</form>
{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/new_topic.html
{% extends "base.html" %} {% block content %}
<p>Adicione um novo tópico:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %} {{ form.as_p }}
    <button name="submit">adicionar tópico</button>
</form>
{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/teste.html
<h1>TESTEEEEEEEEEEE</h1>

<p><a href="{% url 'learning_logs:index' %}">hjkdhakjsdhkjahdkjaksjda</a></p>

django/learning_log/learning_log/learning_logs/templates/topic.html
{% extends 'base.html' %}

{% block content %}
(...)

<ul>
{% for entry in entries %}
<li>
<p>{{ entry.date_added|date:'d M, Y H:i' }}</p>
<p>{{ entry.text|linebreaks }}</p>
<p>
<a href="{% url 'learning_logs:edit_entry' entry.id %}">editar entrada</a>
</p>

</li>
{% empty %}
<li>Ainda não há entradas para este tópico.</li>
{% endfor %}
</ul>
{% endblock content %}

django/learning_log/learning_log/learning_logs/templates/topics.html
{% extends "base.html" %}
{% block content %}
<p>Tópicos</p>
<ul>
    {% for topic in topics %}
        <li>
<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</li>
    {% empty %}
        <li>Você não adicionou nenhum tópico ainda.</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Adicionar novo tópico:</a>

{% endblock content %}